# 博客主题
theme: jekyll-theme-midnight

# site (变量设置)-------------------------
# 网站标题
title: 爱阅坊
# 网站描述
# description: [.....]
google_analytics:

# 插件
plugins:
  - jekyll-remote-theme


# 定义分类生成目录
# permalink: /:categories/:title/
# permalink: /:year/:month/:day/:title:output_ex
