# 博客主题
theme: jekyll-theme-minimal

# 插件
plugins:
- jekyll-remote-theme

# site (变量设置)-------------------------
# 网站标题
title: 爱阅坊
# 网站描述
# description: [.....]

menu:
  home: / || 首页
  categories: /categories/ || 分类
  tags: /tags/ || 标签
