name: Building-GitHub-page
on:
  push:
  pull_request:
    types: [opened, synchronize]

env:
  DELETE_OLD_WORKFLOW: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: build
        run: script/bootstrap
      - name: test
        run: script/cibuild
      - name: Delete old Workflow Runs
        uses: GitRML/delete-workflow-runs@main
        if: env.DELETE_OLD_WORKFLOW == 'true'
        with:
          retain_days: 1
          keep_minimum_runs: 3
