name: Delete-old-Workflow

on:
  workflow_dispatch:


env:
  DELETE_OLD_WORKFLOW: true
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 5120
        swap-size-mb: 512
        remove-dotnet: 'true'
        remove-android: 'true'
      - name: Delete old Workflow Runs
        uses: GitRML/delete-workflow-runs@main
        if: env.DELETE_OLD_WORKFLOW == 'true'
        with:
          retain_days: 2
          keep_minimum_runs: 4
